### ISSUE TITLE
Corner Vision Doesn't run Parallel to Terrain Wall

### ISSUE THREAD

**Issue by maplealmond** [eadorin/point-of-vision#2]
I am not sure if this is an issue specifically solve-able by the Corner Vision mod

When a token is standing in a doorway, by the D&D 4th Edition rules it should be able to see the entire room because the corners are just inside the room and vision should run parallel to the doors.  In reality, the vision looks more like this.

https://i.imgur.com/FzkLEja.png

The walls in this case were drawn with a snap-to-grid.

Curiously, all midpoints looks very much like all corners, and different than merely selecting midpoint top.

This can be replicated by any one-gap hole created by terrain walls.

**Comment by Morchaoron** [comment]
It seems it only works when you select a single corner, but it doesn't work with 'All Corners'
